apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: knative-spring-mvc
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            autoscaling.knative.dev/metric: concurrency
            autoscaling.knative.dev/target: "10"
            autoscaling.knative.dev/maxScale: "3"
        spec:
          containers:
            image: docker.io/ajittua/knative-spring-mvc:blue
            env:
              - name: TARGET
                value: "blue"


